language: go

go:
  - master # This uses automatically the latest version of go

install:
  - go get github.com/spf13/hugo # This provides the latest version of Hugo to Travis CI

script:
  - hugo # This commands builds your website on travis

deploy:
  repo: Zomzog/zomzog.github.io.git
  provider: pages
  skip_cleanup: true
  local_dir: public # Default static site output dir for Hugo
  target_branch: master
  github_token: $GITHUB_TOKEN # This is the authentication which you will setup in the next step in travis-ci dashboard
  on:
    branch: master