language: go

env:
  global:
    - PATH="$TRAVIS_BUILD_DIR/go/bin:$PATH"
    
install:
  - gem install asciidoctor       
  - go get -v github.com/kardianos/govendor
  - govendor get -v github.com/spf13/hugo

script:
  - hugo version
  - hugo -v

after_success: |
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # This generates a `web` directory containing the website.
    cd public
    git init
    git checkout -b master
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://Zomzog:$GITHUB_TOKEN@github.com/zomzog/zomzog.github.io.git master &2>/dev/null
  fi  