language: python

python:
    - "3.6"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -yq install apt-transport-https

# install - install any dependencies required
install:
    - gem install asciidoctor
    # install latest release version
    - wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -r -n '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p;q}}' | xargs wget
    - sudo dpkg -i hugo*.deb
    - rm -rf public 2> /dev/null

script:
  - hugo version
  - hugo -v

after_success: |
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # This generates a `web` directory containing the website.
    cd public
    git init
    git checkout -b master
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://Zomzog:$GITHUB_TOKEN@github.com/zomzog/zomzog.github.io.git master &2>/dev/null
  fi  
